development:
  adapter: postgresql
  encoding: utf8
  database: url_shortener_v2_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: url_shortener_v2_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: url_shortener_v2_production
  pool: 5
  username:
  password:
